import { useState } from "react";

import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import CarForm from "@/lib/CarForm";
import SearchForm from "@/lib/SearchForm";
import { NEXT_URL } from "../config/index";
export default function Home(props) {
    const [cars, setCars] = useState(props.cars);

    console.log(cars);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1 className="text-3xl font-bold underline"> hellp app</h1>
            {cars?.map((car, i) => {
                return (
                    <div key={i}>
                        {car.make}, {car.model}
                    </div>
                );
            })}
            <div className="flex">
                <div className="lg:w-1/2">
                    <CarForm setCars={setCars} />
                </div>
                <div className="lg:w-1/2">
                    <SearchForm />
                </div>
            </div>
        </div>
    );
}

export const getServerSideProps = async (context) => {
    // const { coinId } = context.params;

    const res = await fetch(`${NEXT_URL}/api/getCars`);

    const result = await res.json();

    // console.log(cars);

    // setHits(result["cars"]);

    return {
        props: {
            cars: result["cars"],
        },
    };
};
